// MOTOR DIRECTION
#define MOTORDIR_0 -1
#define MOTORDIR_1 1

// CONTROLLER
#define KP_BALANCE 0.55
#define KD_BALANCE -0.045

// SCHEDULING
#define CONTROLLER_INTERVAL 10
#define ACTIVATION_INTERVAL 50

// SERIAL
#define BAUDRATE_ODRIVE 115200
#define BAUDRATE_PC 115200
